In [5]:
import numpy as np

a=np.array([0,1,2,3]) #벡터(행 1인 행렬)
b=np.array([4,5,6,7])
c=np.array([[0,1,2,3],
           [4,5,6,7]]) #행렬 ( [ [],[] ] )
d=np.zeros((2,4)) #(tuple of ints)
e=np.random.rand(2,5)

print(a)
print(b)
print(c)
print(d)
print(e)

print('연산 calculation')
print('numpy : 연산자를 만나면 변수를 자동 형식 추론해 알맞은 연산 수행 ')
print('따라서 numpy코드를 읽을 때 변수의 shape를 유의해야한다.')
print('요소별 연산 : 두 변수의 열의 개수가 같음, 혹은 한 변수의 열이 1개(scalar)')
print(a * 0.1) # 모든 수 0.1곱
print(a * b) # 열끼리 짝지어서 요소별 곱
print(a * c) # c의 모든 행에 대해 열끼리 요소별 곱
# print(a * e) # 열 개수 불일치 에러


[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.20957508 0.82628999 0.2034137  0.2995852  0.57746968]
 [0.20483578 0.5555715  0.90793172 0.08337575 0.04886199]]
연산 calculation
numpy : 연산자를 만나면 변수를 자동 형식 추론해 알맞은 연산 수행 
따라서 numpy코드를 읽을 때 변수의 shape를 유의해야한다.
요소별 연산 : 두 변수의 열의 개수가 같음, 혹은 한 변수의 열이 1개(scalar)
[0.  0.1 0.2 0.3]
[ 0  5 12 21]
[[ 0  1  4  9]
 [ 0  5 12 21]]


In [6]:

print('행렬 곱,내적 matrix multiplication')
print('(a,b).dot(b,c)=(a,c) 앞쪽 열의개수=뒤쪽 행의 개수')
a=np.zeros((1,4))
b=np.zeros((4,3))
c=a.dot(b)
print(c.shape)

a=np.zeros((2,4))
b=np.zeros((4,3))
c=a.dot(b)
print(c.shape)

e=np.zeros((2,1))
f=np.zeros((1,3))
g=e.dot(f)
print(g.shape)

h=np.zeros((5,4)).T #.T flips the rows and columns of a matrix
i=np.zeros((5,6))
j=h.dot(i)
print(j.shape)

h=np.zeros((5,4))
i=np.zeros((5,6))
#j=h.dot(i) # rule에 맞지 않아 에러를 던짐
#print(j.shape)

행렬 곱,내적 matrix multiplication
(a,b).dot(b,c)=(a,c) 앞쪽 열의개수=뒤쪽 행의 개수
(1, 3)
(2, 3)
(2, 3)
(4, 6)
