In [ ]:
# 라이브러리 사용
import pandas as pd
import tensorflow as tf



In [ ]:
# 1. 과거의 데이터 준비
path='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴=pd.read_csv(path)

# 독립 , 종속 분리
독립=보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속=보스턴[['medv']]
print(독립.shape, 종속.shape) # 확인 체크 잊지 말기! 버그 적게 할 수 있음

(506, 13) (506, 1)


In [ ]:
# 2. 모델의 구조 만들기
X= tf.keras.layers.Input(shape=[13])
H= tf.keras.layers.Dense(10, activation='swish')(X)
Y=tf.keras.layers.Dense(1)(H)
model=tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [ ]:
model.summary() # 모델 모양 확인

Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 3. 데이터로 모델을 학습(fit)
#model.fit(독립, 종속, epochs=1000,verbose=0)
model.fit(독립, 종속, epochs=100)

In [ ]:
# 4. 모델 이용
print(model.predict(독립[:5])) # 0~5번째 까지 잘라서
print(종속[:5])

[[35.134735]
 [26.88185 ]
 [31.292688]
 [33.265766]
 [31.313534]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [ ]:
# 가중치 확인
print(model.get_weights())

**아이리스 품종 분류**

In [ ]:
# 1. 과거 데이터
path='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris=pd.read_csv(path)

# onehot encoding
인코딩=pd.get_dummies(iris)

# 독립, 종속
독립= 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속= 인코딩[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
# 2. 모델의 구조 만들기
X=tf.keras.layers.Input(shape=[4])
H= tf.keras.layers.Dense(8, activation='swish')(X)  # 8개 노드를 가진 히든 레이어1
H= tf.keras.layers.Dense(8, activation='swish')(H)  # 2
H= tf.keras.layers.Dense(8, activation='swish')(H)  # 3
Y=tf.keras.layers.Dense(3, activation='softmax')(H)
model=tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

In [ ]:
print(model.summary())

Model: "functional_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
# FIT
model.fit(독립, 종속, epochs=100)

In [ ]:
# model이용
print(model.predict(독립[:5]))
print(종속[:5])

[[9.8312873e-01 1.6746812e-02 1.2443481e-04]
 [9.7811478e-01 2.1676503e-02 2.0867979e-04]
 [9.8173308e-01 1.8092144e-02 1.7474081e-04]
 [9.7548103e-01 2.4277532e-02 2.4139771e-04]
 [9.8365223e-01 1.6228242e-02 1.1953631e-04]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
# 가중치 확인
print(model.get_weights())

[array([[ 0.1508997 , -0.07835476,  0.12694658, -0.7474563 ,  0.9534981 ,
        -0.0194805 ,  0.091174  , -0.6120778 ],
       [-0.14905417, -0.26583275, -0.7025895 , -0.24241817,  0.93840694,
         0.03422035, -0.1121344 ,  0.4829096 ],
       [-0.4658035 , -0.1485795 , -0.5200598 ,  0.5612058 ,  0.46729657,
        -0.5140194 ,  0.8884368 ,  0.13919497],
       [-0.9123818 , -0.5636109 , -0.42745966,  0.34894034,  0.21561834,
        -0.22418757,  0.5357497 , -0.68436366]], dtype=float32), array([ 0.14370641,  0.38342464, -0.15710273, -0.33341956,  0.28000376,
        0.18709947, -0.27946573,  0.20016195], dtype=float32), array([[ 0.05268998, -0.7474117 ,  0.15972424,  0.82672215, -0.8636974 ,
         0.18125509, -0.40384212, -0.9188177 ],
       [-0.49772325, -0.5687169 , -0.51907885,  0.5702836 , -0.31698298,
        -0.13016923,  0.03165143, -0.45117268],
       [-0.072107  , -0.15031742, -0.61246455,  0.21221215,  0.20460165,
         0.2195356 ,  0.44648278, -0.73503757],
